package com.firstopiniondentist.main;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.TextView;

import com.firstopiniondentist.firstopiniondentist.R;

public class TermsActivity extends AppCompatActivity {

    private static String terms_Text = "\n" +
            "Use of the Mobile App Dental Care, Inc. (“Dental Care”, “we”, “us”, or “our”) operates the iOS and Android mobile applications and website located at www.DentalCareApp.com and other related applications with links to these Terms of Use (collectively, the “Mobile App”). We offer online telehealth services (the “Services”) enabling our members (“Members”) to report their health history and engage healthcare professionals (“Treating Providers”) to obtain dental and healthcare services (“Services”). By accessing and using the Mobile App / mobile application, you agree to be bound by these Terms of Use and all other terms and policies that appear on the Mobile App. If you do not wish to be bound by any of these Terms of Use you may not use the Mobile App or the Services.\n" +
            "Healthcare Services. All of the Treating Providers who deliver Services through Dental Care are independent professionals solely responsible for the services each provides to you. Neither Dental Care nor any third parties who promote the Services or provide you with a link to the Service shall be liable for any professional advice you obtain from a Treating Provider via the Services.\n" +
            "Mobile App Content. None of the Mobile App content should be considered medical advice or an endorsement, representation or warranty that any particular medication or treatment is safe, appropriate, or effective for you.\n" +
            "Informed Consent:\n" +
            "A. Telehealth is the delivery of dental services using interactive audio and video technology, where the patient and the dental professional are not in the same physical location. During your telehealth consultation with a Treating Provider, details of your health history and personal health information may be discussed with you through the use of interactive video, audio and other telecommunications technology, and your Treating Provider may perform a physical examination through these technologies.\n" +
            "B. The telehealth Services you receive from Treating Providers are not intended to replace a primary care Dental relationship or be your permanent medical home. However, your initial visit with a Treating Provider will begin as a consultation (e.g. to determine the most appropriate treatment setting for you to receive care) and will not necessarily give rise to an ongoing treatment relationship. You should seek emergency help or follow-up care when recommended by a Treating Provider or when otherwise needed, and continue to consult with your primary care Dental and other healthcare professionals as recommended. We may make arrangements for follow-up care either through Dental Care or other healthcare providers. Among the benefits of our Services are improved access to healthcare professionals and convenience. However, as with any health service, there are potential risks associated with the use of telehealth. These risks include, but may not be limited to:\n" +
            "In rare cases, information transmitted may not be sufficient (e.g. poor resolution of images) to allow for appropriate dental decision making by the Treating Provider;\n" +
            "Delays in evaluation or treatment could occur due to failures of the electronic equipment. If this happens, you may be contacted by phone or other means of communication.\n" +
            "In rare cases, a lack of access to all of your health records may result in adverse drug interactions or allergic reactions or other judgment errors;\n" +
            "Although the electronic systems we use will incorporate network and software security protocols to protect the privacy and security of health information, in rare instances, security protocols could fail, causing a breach of privacy of personal health information.\n" +
            "C. By accepting these Terms of Use, you acknowledge that you understand and agree with the following:\n" +
            "You understand that you may expect the anticipated benefits from the use of telehealth in your care, but that no results can be guaranteed or assured.\n" +
            "If your health insurance coverage does not include or is not sufficient to satisfy the Services charges in full, you may be fully responsible for payment.\n" +
            "Your treating provider may determine that the Services are not appropriate for some or all of your treatment needs, and accordingly may elect not to provide telehealth services to you through the Mobile App.\n" +
            "D. You can send messages to your Treating Provider by contacting Dental Care Customer Support. Emails or electronic messages to Customer Support or your Treating Provider may not be returned immediately. If you are experiencing a medical emergency, you should call 911 or go to the nearest emergency room.\n" +
            "E. You may also be able to send written notes to therapists or other Treating Providers or to Customer Support using a secure messaging portal within the Mobile App (the “Messaging Portal”). Messages you send over the Messaging Portal may be viewed by more than one Treating Provider or Customer Support agent and will typically be answered within 48 hours. You should not rely on the Messaging Portal if you need immediate attention from a Treating Provider or other dental professional. If you are experiencing a medical emergency, you should call 911 or go to the nearest emergency room. You understand and agree that messaging with Treating Providers over the Messaging Portal does not give rise to a provider-patient relationship, and does not by itself constitute treatment, diagnosis, therapy, or medical advice.\n" +
            "Privacy: The information you provide to your Treating Provider during a medical consultation or therapy session is confidential, except for certain legal exceptions as more fully described in our Notice of Privacy Practices. We devote considerable effort toward ensuring that your personal information is secure. Information regarding our use of health and other personal information is provided in our Site Privacy Policy and health information Notice of Privacy Practices. As part of providing you the Services, we may need to provide you with certain communications, such as appointment reminders, service announcements and administrative messages. These communications are considered part of the Services and your Account. While secure electronic messaging is always preferred to insecure email, under certain circumstances, insecure email communication containing personal health information may take place between you and Dental Care. Dental Care cannot ensure the security or confidentiality of messages sent by email. Information relating to your care, including clinical notes and medical records, are stored on secure servers maintained by Dental Care.\n" +
            "User Accounts. When you register on the site or mobile application, you are required to create an account (“Account”) by entering your name, email address, password and certain other information collected by Dental Care (collectively “Account Information”). To create an Account, you must be of legal age to form a binding contract. If you are not of legal age to form a binding contract, you may not register to use our Services. You agree that the Account Information that you provide to us at all times, including during registration and in any information you upload to the Site/Mobile Application will be true, accurate, current, and complete. You may not transfer or share your Account password with anyone, or create more than one Account (with the exception of subaccounts established for children of whom you are the parent or legal guardian). You are responsible for maintaining the confidentiality of your Account password and for all activities that occur under your Account. Dental Care reserves the right to take any and all action, as it deems necessary or reasonable, regarding the security of the Site/Mobile Application and your Account Information. In no event and under no circumstances shall Dental Care be held liable to you for any liabilities or damages resulting from or arising out of your use of the Site/Mobile Site, your use of the Account Information or your release of the Account Information to a third party. You may not use anyone else's account at any time.\n" +
            "Use of the Services by Children. The Services are available for use by children, but the Member for all patients under the age of 18 must be the patient’s parent or legal guardian. If you register as the parent or legal guardian on behalf of a minor, you will be fully responsible for complying with these Terms of Use.\n" +
            "Access Rights. We hereby grant to you a limited, non-exclusive, nontransferable right to access the Mobile App and use the Services solely for your personal non-commercial use and only as permitted under these Terms of Use and any separate agreements you may have entered into with us (“Access Rights”). We reserve the right, in our sole discretion, to deny or suspend use of the Mobile App or Services to anyone for any reason. You agree that you will not, and will not attempt to: (a) impersonate any person or entity, or otherwise misrepresent your affiliation with a person or entity; (b) use the Mobile App or Services to violate any local, state, national or international law; (c) reverse engineer, disassemble, decompile, or translate any software or other components of the Mobile App or Services; (d) distribute viruses or other harmful computer code through the Mobile App or (e) otherwise use the Services or Mobile App in any manner that exceeds the scope of use granted above. In addition, you agree to refrain from abusive language when communicating with Treating Providers through the Mobile App and to refrain from contacting Treating Providers for telehealth services outside of the Mobile App. Dental Care is not responsible for any interactions with Treating Providers that are not conducted through the Mobile App. We strongly recommend that you do not use the Services on public computers. We also recommend that you do not store your Account password through your web browser or other software.\n" +
            "Fees and Purchase Terms. You agree to pay all fees or charges to your Account in accordance with the fees, charges, and billing terms in effect at the time a fee or charge is due and payable. By providing Dental Care with your credit card number or PayPal account and associated payment information, you agree that Dental Care is authorized to immediately invoice your account for all fees and charges due and payable to Dental Care hereunder and that no additional notice or consent is required. If your health plan, employer or agency has arranged with Dental Care to pay the fee or any portion of the fee, or if the fee is pursuant to some other arrangement with Dental Care, that fee adjustment will be reflected in the fee that you are ultimately charged. Please check with your employer, health plan or agency to determine if any Services will be reimbursed.\n" +
            "If you do not have insurance coverage for Services, or if your coverage is denied, you acknowledge and agree that you shall be personally responsible for all incurred expenses. Dental Care offers no guarantee that you shall receive any such reimbursement. Dental Care reserves the right to modify or implement a new pricing structure at any time prior to billing you for your initial payment or for future payments due pursuant to these Terms of Use. You understand and agree that for Services provided on an appointment basis, you will be responsible for a missed appointment fee equal to the fees you and your insurer or other payor would have paid for the scheduled services if you do not cancel a scheduled appointment at least 24 hours in advance.\n" +
            "Website Links: We will not be liable for any information, software, or links found at any other website, internet location, or source of information, nor for your use of such information, software or links nor for the acts or omissions of any such websites or their respective operations. \n" +
            "Ownership. The Mobile App and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by the Company, its licensors or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. These Terms of Use permit you to use the Mobile App for your personal, non-commercial use only. You must not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store or transmit any of the material on our Mobile App except as generally and ordinarily permitted through the Mobile App according to these Terms of Use. You must not access or use for any commercial purposes any part of the Mobile App or any services or materials available through the Mobile App.\n" +
            "Trademarks. Certain of the names, logos, and other materials displayed on the Mobile App or in the Services may constitute trademarks, trade names, service marks or logos (\"Marks\") of Dental Care or other entities. You are not authorized to use any such Marks without the express written permission of Dental Care. Ownership of all such Marks and the goodwill associated therewith remains with us or those other entities.\n" +
            "Termination. You may deactivate your Account and end your registration at any time, for any reason by sending an email to support@Dental Care.com. Dental Care may suspend or terminate your use of the Mobile App, your Account and/or registration for any reason at any time. Subject to applicable law, Dental Care reserves the right to maintain, delete or destroy all communications and materials posted or uploaded to the Mobile App pursuant to its internal record retention and/or content destruction policies. After such termination, Dental Care will have no further obligation to provide the Services, except to the extent we are obligated to provide you access to your health records or Treating Providers are required to provide you with continuing care under their applicable legal, ethical and professional obligations to you.\n" +
            "Right to modify. We may at our sole discretion change, add, or delete portions of these Terms of Use at any time on a going-forward basis. Continued use of the Mobile App and/or Services following notice of any such changes will indicate your acknowledgement of such changes and agreement to be bound by the revised Terms of Use, inclusive of such changes.\n" +
            "DISCLAIMER OF WARRANTIES. YOU EXPRESSLY AGREE THAT USE OF THE MOBILE APP OR SERVICES IS AT YOUR SOLE RISK. BOTH THE MOBILE APP AND SERVICES ARE PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS. DENTAL CARE EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE, NON-INFRINGEMENT, TITLE, OPERABILITY, CONDITION, QUIET ENJOYMENT, VALUE, ACCURACY OF DATA AND SYSTEM INTEGRATION.\n" +
            "You acknowledge and agree that Dental Care does not provide medical advice, diagnosis, or treatment, and is strictly a technology platform and infrastructure for connecting patients with independent third party Treating Providers, including Dentals and other Treating Providers in the Dental Care network. You acknowledges and agree that the Treating Providers using the Mobile App are solely responsible for and will have complete authority, responsibility, supervision, and control over the provision of all medical services, advice, instructions, treatment decisions, and other professional dental services performed, and that all diagnoses, treatments, procedures, and other professional dental services will be provided and performed exclusively by or under the supervision of Treating Providers, in their sole discretion, as they deem appropriate.\n" +
            "LIMITATION OF LIABILITY. YOU UNDERSTAND THAT TO THE EXTENT PERMITTED UNDER APPLICABLE LAW, IN NO EVENT WILL DENTAL CARE OR ITS OFFICERS, EMPLOYEES, DIRECTORS, PARENTS, SUBSIDIARIES, AFFILIATES, AGENTS OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF REVENUES, PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES ARISING OUT OF OR RELATED TO YOUR USE OF THE MOBILE APP OR THE SERVICES, REGARDLESS OF WHETHER SUCH DAMAGES ARE BASED ON CONTRACT, TORT (INCLUDING NEGLIGENCE AND STRICT LIABILITY), WARRANTY, STATUTE OR OTHERWISE. To the extent that we may not, as a matter of applicable law, disclaim any implied warranty or limit its liabilities, the scope and duration of such warranty and the extent of our liability will be the minimum permitted under such applicable law.\n" +
            "Indemnification. You agree to indemnify, defend and hold harmless Dental Care, its officers, directors, employees, agents, subsidiaries, affiliates, licensors, and suppliers, harmless from and against any claim, actions, demands, liabilities and settlements, including without limitation reasonable legal and accounting fees (“Claims”), resulting from, or alleged to result from, your violation of these terms and conditions. In addition, you agree to indemnify, defend and hold harmless your Treating Provider(s) from and against any third party Claims resulting from your lack of adherence with the advice or recommendation(s) of such Treating Provider.\n" +
            "Geographical Restrictions. Dental Care makes no representation that all products, services and/or material described on the Mobile App, or the Services available through the Mobile App, are appropriate or available for use in locations outside the United States or all territories within the United States.\n" +
            "Disclosures.\n" +
            "All Dentists on the site / mobile application hold professional licenses issued by the professional licensing boards in the states where they practice, hold Dental degrees of D.M.D. or D.D.S. and have undergone post-Dental School training. \n" +
            "Any clinical records created as a result of your use of the site / mobile app will be securely maintained by Dental Care on behalf of your Treating Provider(s) for a period that is no less than the minimum number of years such records are required to be maintained under state and federal law.\n" +
            "\n" +
            "\n" +
            "Miscellaneous.\n" +
            "These Terms of Use and your use of the Mobile App shall be governed by the laws of the State of Delaware, without giving effect to the principles of conflict of laws. Any dispute arising under or relating in any way to these Terms of Use will be resolved exclusively by final and binding arbitration in San Francisco, California under the rules of the American Arbitration Association, except that either party may bring a claim related to intellectual property rights, or seek temporary and preliminary specific performance and injunctive relief, in any court of competent jurisdiction, without the posting of bond or other security. The parties agree to the personal and subject matter jurisdiction and venue of the courts located in San Francisco, California, for any action related to these Terms of Use.\n" +
            "Your understand that by checking the “agree” box for these Terms of Use and/or any other forms presented to you on the Mobile App you are agreeing to these Terms of Use and that such action constitutes a legal signature. You agree that we may send to you any privacy or other notices, disclosures, or communications regarding the Services (collectively, \"Communications\") through electronic means including but not limited to: (1) by e-mail, using the address that you provided to us during registration, or (2) by posting the Communications on the Mobile App. The delivery of any Communications from us is effective when sent by us, regardless of whether you read the Communication when you receive it or whether you actually receive the delivery. You can withdraw your consent to receive Communications by email by canceling or discontinuing your use of the Service.\n" +
            "No waiver by the Company of any term or condition set forth in these Terms of Use shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of the Company to assert a right or provision under these Terms of Use shall not constitute a waiver of such right or provision. If any provision of these Terms of Use is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms of Use will continue in full force and effect.\n" +
            "Dental Care devotes considerable effort to optimizing signal strength and diagnosis deficiencies but is not responsible for the internet or data bandwidth and signal of your mobile device.\n" +
            "Please report any violations of these Terms of Use to Dental Care Management. \n" +
            "The Digital Millennium Copyright Act of 1998 (the \"DMCA\") provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. If you believe in good faith that materials appearing on this Web Site & Mobile App infringe your copyright, you (or your agent) may send us a notice requesting that the material be removed, or access to it blocked. In addition, if you believe in good faith that a notice of copyright infringement has been wrongly filed against you, the DMCA permits you to send us a counter-notice. Notices and counter-notices must meet statutory requirements imposed by the DMCA. One place to find more information is the U.S. Copyright Office Web Site & Mobile App, currently located at http://www.loc.gov/copyright. In accordance with the DMCA, Dental Care has designated an agent to receive notification of alleged copyright infringement in accordance with the DMCA. Any written Notification of Claimed infringement should comply with Title 17, United States Code, Section 512(c)(3)(A) and should be provided in writing to Dental Care, Inc., 275 Battery Street Suite 650, San Francisco, CA 94111.\n" +
            "Notice of Health Information Privacy Practices\n" +
            "This notice describes how medical information about you may be used and disclosed and how you can get access to this information. Please review it carefully.\n" +
            "How is Patient Privacy Protected?\n" +
            "As the healthcare providers providing online medical services through Dental Care (the “Healthcare Providers”, “us”, “we”, “our”), we understand that information about you and your health is personal.  Because of this, we strive to maintain the confidentiality of your health information.  We continuously seek to safeguard that information through administrative, physical and technical means, and otherwise abide by applicable federal and state guidelines.\n" +
            "How do we use and disclose health information?\n" +
            "We use and disclose your health information for the normal business activities that the law sees as falling in the categories of treatment, payment and dental operations.  Below we provide examples of those activities, although not every use or disclosure falling within each category is listed:\n" +
            "Treatment – We keep a record of the health information you provide us. This record may include your test results, diagnoses, medications, your response to medications or other therapies, and information we learn about your medical condition through the online services.  We may disclose this information so that other Dentists, nurses, and entities such as laboratories can meet your healthcare needs.  \n" +
            "Payment – We document the services and supplies you receive when we are providing care to you so that you, your insurance company or another third party can pay us.  We may tell your health plan about upcoming treatment or services that require prior approval by your health plan.  \n" +
            "Dental Operations – Health information is used to improve the services we provide, to train staff and students, for business management, quality improvement, and for customer service.  For example, we may use your health information to review our treatment and services and to evaluate the performance of our staff in caring for you.\n" +
            "We may also use your health information to:\n" +
            "Comply with federal, state or local laws that require disclosure.\n" +
            "Assist in public health activities such as tracking diseases or medical devices.\n" +
            "Inform authorities to protect victims of abuse or neglect.\n" +
            "Comply with Federal and state health oversight activities such as fraud investigations.\n" +
            "Respond to law enforcement officials or to judicial orders, subpoenas or other process.  \n" +
            "Inform coroners, medical examiners and funeral directors of information necessary for them to fulfill their duties.\n" +
            "Facilitate organ and tissue donation or procurement.\n" +
            "Conduct research following internal review protocols to ensure the balancing of privacy and research needs.\n" +
            "Avert a serious threat to health or safety.\n" +
            "Assist in specialized government functions such as national security, intelligence and protective services.\n" +
            "Inform military and veteran authorities if you are an armed forces member (active or reserve).\n" +
            "Inform a correctional institution if you are an inmate.\n" +
            "Inform workers’ compensation carriers or your employer if you are injured at work.\n" +
            "Recommend treatment alternatives.\n" +
            "Tell you about health-related products and services.\n" +
            "Communicate within our organization for treatment, payment, or dental operations.\n" +
            "Communicate with other providers, health plans, or their related entities for their treatment or payment activities, or dental operations activities relating to quality assessment or licensing.\n" +
            "Provide information to other third parties with whom we do business, such as a record storage provider.  However, you should know that in these situations, we require third parties to provide us with assurances that they will safeguard your information.\n" +
            "We may also use or disclose your personal or health information for the following operational purposes.              For example, we may Communicate with individuals involved in your care or payment for that care, such as friends and family.\n" +
            "Send appointment reminders.\n" +
            "You may tell us that you do not want us to use or disclose your information for these two activities.\n" +
            "All other uses and disclosures, not previously described, may only be done with your written authorization.  For example, we need your authorization before we disclose your psychotherapy notes.  We will also obtain your authorization before we use or disclose your health information for marketing purposes or before we would sell your information.  You may revoke your authorization at any time; however, this will not affect prior uses and disclosures.\n" +
            "\n" +
            "We reserve the right to change privacy practices, and make the new practices effective for all the information we maintain.  Revised notices will be posted on the Dental Care website & Mobile App.\n" +
            "Do you have any Federal Rights?\n" +
            "The law entitles you to: Inspect and copy certain portions of your health information.  If we keep records electronically, you may request that we provide them to you in an electronic format.\n" +
            "Request amendment of your health information if you feel the health information is incorrect or incomplete.  (However, under certain circumstances we may deny your request.)\n" +
            "Receive an accounting of certain disclosures of your health information made for the prior six (6) years, although this excludes disclosures for treatment, payment, dental operations. (Fees may apply to this request).\n" +
            "Request that we restrict how we use or disclose your health information.  (However, we are not required to agree with your requests, unless you request that we restrict information provided to a payor, the disclosure would be for the payor’s payment or dental operations, and you have paid for the dental services completely out of pocket).\n" +
            "Request that we communicate with you at a specific telephone number or address.\n" +
            "Obtain a paper copy of this notice even if you receive it electronically.\n" +
            "Who Will Follow This Notice?\n" +
            "This Notice describes the healthcare practices of:\n" +
            "Any Dental or other dental professional authorized by us to access and/or enter information into your medical record, all departments and units through which Dental Care’s online services are provided; and\n" +
            "\n" +
            "Your personal care providers may have different policies or Notices regarding their use and disclosure of your health information created in their offices.\n" +
            "Dental Care Site & Mobile App Privacy Policy\n" +
            "Last revised 3/19/2016.\n" +
            "Introduction.  Dental Care, Inc. (“Dental Care”, “we”, “us”, or “our”) operates the website located at www.Dental Care.com and other related websites and mobile applications with links to this Privacy Policy (collectively, the “Site”).  Through the Website & mobile app, we operate an online service enabling members (“Members”) to receive telehealth services from various healthcare providers (the “Services”).  We developed this privacy policy (“Privacy Policy”) to explain how we collect, use, and disclose information from and/or about you when you use the Website, mobile app or the Services.  \n" +
            "THE WEBSITE & MOBILE APP WILL BE COLLECTING AND TRANSMITTING PERSONAL, MEDICAL AND HEALTH-RELATED INFORMATION ABOUT YOU.   BY USING THE WEBSITE & MOBILE APP, YOU AGREE THAT WE CAN COLLECT AND USE YOUR PERSONAL AND OTHER INFORMATION AS DESCRIBED IN THIS PRIVACY POLICY.   IF YOU DO NOT AGREE, PLEASE DO NOT USE THE SITE & MOBILE APPLICATION.\n" +
            "Important Definitions.  When we use the term “Personal Information” in this Privacy Policy, we mean information about you that is personally identifiable to you, such as your contact information (e.g., name, address, email address, or telephone number), personally identifiable health or medical information (“Health Information”), and any other non-public information that is associated with such information (collectively, “Personal Information”).  When we use the term “De-Identified Information”, we mean information that is neither used nor intended to be used to personally identify an individual.  Lastly, when we use the term “Cookies”, we mean the small pieces of information that a Website & mobile app sends to your browser while you are viewing a website.  \n" +
            "Questions:  If you have questions or concerns about this Privacy Policy, please contact us by sending an email.\n" +
            "HIPAA:   Our privacy practices are intended to comply with the Health Insurance Portability and Accountability Act (\"HIPAA\").  We will maintain the privacy of your Health Information as required by HIPAA and the regulations promulgated under that Act. We encourage you to review our Notice of Privacy Practices, which describes how we may use and disclose your Health Information.\n" +
            "Children under age 18.  We do not knowingly allow individuals under the age 18 to create Accounts that allow access to our Website & mobile app.\n" +
            "The Personal information we collect or maintain may include:\n" +
            "Your name, age, email address, username,  password, and other registration information  \n" +
            "Health Information that you provide us, which may include information or records relating to your medical or health history, health status and laboratory testing results, diagnostic images, and other health related information.\n" +
            "Information about the computer or mobile device you are using, such as what Internet browser you use, the kind of computer or mobile device you use, and other information about how you use the Website & mobile app. Other information you input into the Website, mobile app or related services.\n" +
            "We may use your Personal Information for the following purposes (subject to applicable legal restrictions):\n" +
            "\n" +
            "To provide you with the Services\n" +
            "To improve the quality of healthcare through the performance of quality reviews and similar activities\n" +
            "To create De-identified Information such as aggregate statistics relating to the use of the Service\n" +
            "To notify you when Website and mobile app updates are available,\n" +
            "To market and promote the Website and mobile app and the Services\n" +
            "To fulfill any other purpose for which you provide us Personal Information  \n" +
            "For any other purpose for which you give us authorization  \n" +
            "\n" +
            "We may also disclose Personal Information that we collect or you provide (subject to applicable legal restrictions):\n" +
            "\n" +
            "To our subsidiaries and affiliates.\n" +
            "To contractors, service providers and other third parties we use to support our business and who are bound by contractual obligations to keep personal information confidential and use it only for the purposes for which we disclose it to them. \n" +
            "As required by law, which can include providing information as required by a court order.\n" +
            "When we believe in good faith that disclosure is necessary to protect your safety or the safety of others to protect our rights, to investigate fraud, or to respond to a government request.\n" +
            "To a buyer or other successor in the event of a merger, divestiture, restructuring, reorganization, dissolution or other sale or transfer of some or all of Dental Care’s assets, whether as a going concern or as part of bankruptcy, liquidation or similar proceeding, in which Personal Information maintained by the Website and mobile app is among the assets transferred.\n" +
            "For any other purpose disclosed by us when you provide the information.\n" +
            "Information We Collect via Technology. As you use the Website and mobile app or the Service, certain information may be passively collected by Cookies, navigational data like Uniform Resource Locators (URLs) and third party tracking services, including:\n" +
            "Website and mobile app Activity Information.  We may keep track of some of the actions you take on the Website and mobile app, such as the content of searches you perform on the Website and mobile app.\n" +
            "Access Device and Browser Information.  When you access the Website and mobile app from a computer or other device, we may collect anonymous information from that device, such as your Internet protocol address, browser type, connection speed and access times (collectively, “Anonymous Information”).\n" +
            "Cookies.  We may use both session Cookies (which expire once you close your web browser) and persistent Cookies to make the Mobile app and Service easier to use, to make our advertising better, and to protect both you and Dental Care.  You can instruct your browser, by changing its options, to stop accepting Cookies or to prompt you before accepting a Cookie from the websites you visit. If you do not accept Cookies, however, you will not be able to stay logged in to the Site / Mobile Application.   We presently do not honor  \"Do Not Track\" requests across all part of our Site / Mobile Application.  \n" +
            "Real-Time Location.  Certain features of the Site / Mobile Application use GPS technology to collect real-time information about the location of your device so that the Site & mobile app can connect you to a dental provider who is licensed or authorized to provide services in the state where you are located.\n" +
            "Mobile Services.  We may also collect non-personal information from your mobile device or computer.   This information is generally used to help us deliver the most relevant information to you. Examples of information that may be collected and used include how you use the application(s) and and information about the type of device or computer you use.  In addition, in the event our application(s) crashes on your mobile device we will receive information about your mobile device model software version and device carrier, which allows us to identify and fix bugs and otherwise improve the performance of our application(s).  \n" +
            "Google Analytics.  We use Google Analytics to help analyze how users use the Site / Mobile Application.  Google Analytics uses Cookies to collect information such as how often users visit the Site & mobile app, what pages they visit, and what other Mobile Applications they used prior to coming to the Mobile App. We use the information we get from Google Analytics only to improve our Mobile App and Services. Google Analytics collects only the IP address assigned to you on the date you visit the Mobile App, rather than your name or other personally identifying information.  Although Google Analytics plants a persistent Cookie on your web browser to identify you as a unique user the next time you visit the Mobile App, the Cookie cannot be used by anyone but Google.  Google’s ability to use and share information collected by Google Analytics about your visits to the Mobile App is restricted by the Google Analytics Terms of Use and the Google Privacy Policy.  \n" +
            "De-Identified Information.  We may use De-Identified Information created by us without restriction.    \n" +
            "Information You Share with Third Parties This Privacy Policy applies only to information we collect through the Mobile App and in email, text and other electronic communications set through or in connection with the Mobile App.  This policy DOES NOT apply to information collected by any third party.  When you click on links on the Mobile App you may leave our Mobile App. We are not responsible for the privacy practices of other Mobile Apps, and we encourage you to read their privacy statements.\n" +
            "Modification of Information:  Members will be able to update some of their information through the Mobile App.  Requests to modify any information may also be submitted directly to the Mobile App / mobile application administrator. Limitations on Deletion of Information.  You may request deletion of your Personal Information by us, but please note that we may be required (by law or otherwise) to keep this information and not delete it (or to keep this information for a certain time, in which case we will comply with your deletion request only after we have fulfilled such requirements). When we delete Personal Information, it will be deleted from the active database, but may remain in our archives and we may also retain Anonymous Information about your use of our Service.  Once we disclose some of your Personal Information to third parties, we may not be able to access that Personal Information any longer and cannot force the deletion or modification of any such information by the parties to whom we have made those disclosures.  After we delete Personal Information, we will retain De-Identified Data and will continue to use De-Identified Data as permitted under this Privacy Policy.\n" +
            "Steps we take to keep your information secure. We employ reasonable physical, electronic and managerial security methods to help protect against unauthorized access to Personal Information, such as encryption.    But please be aware that no data transmission over the Internet or data storage facility can be guaranteed to be perfectly secure.  As a result, while we try to protect your Personal Information, we cannot ensure or guarantee the security of any information you transmit to us, and you do so at your own risk.  \n" +
            "Report Violations. You should report any security violations to us by sending an email to Mobile App / mobile application administrators.\n" +
            "\n" +
            "Changes to this Privacy Policy. We may change this Privacy Policy from time to time in the future.  We will post any revised version of the Privacy Policy on this page.  Continued use of our Service following notice of such changes will indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes.  By using the Mobile App, you are agreeing to our collection, use and disposal of Personal Information and other data as described in this Privacy Policy, both as it exists now and as it is changed from time to time.\n" +
            "\n" +
            "\n" +
            "\n";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_terms);


        TextView desc = (TextView)findViewById(R.id.terms);
        desc.setText(terms_Text);

    }

}
